version: "3"

services:
  web:
    build: ./src
    restart: always
    ports:
      - "3000:3000"
    volumes: ['./src:/app']
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      FLASK_DEBUG: 0 
