version: "3"

services:
  web:
    build: ./src
    restart: always
    ports:
      - "5000:5000"
    # volumes: ['./src:/app']  # only for developement
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      FLASK_DEBUG: 0 
      PASSWORD: ThisIsaSecret_CRC_60II
